name: Tests

env:
  GO: 1.16

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO }}

    - name: Make
      run: make -k test
